# Netlify Configuration for Static Site (No Backend)

[build]
  # Build command - frontend only (overrides package.json "build" script)
  command = "npx vite build"
  
  # Publish directory (where Vite outputs the build)
  publish = "dist/public"

# SPA Redirect Rule - serves index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
