# Netlify Configuration for SPA

[build]
  # Build command (builds frontend only - no backend needed)
  command = "npm install && npx vite build"
  
  # Publish directory (where Vite outputs the build)
  publish = "dist/public"

# SPA Redirect Rule - serves index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
